mcm_demo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MCMDemoBundle:Default:index }

mcm_demo_collection_form:
    pattern:  /form/collection
    defaults: { _controller: MCMDemoBundle:Default:collections }